# -*- coding: utf-8 -*-
"""tablero_papers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqfPUX6IrQB0P3DCRztAt0qe4scYFteZ
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from streamlit_gsheets import GSheetsConnection
from datetime import datetime

# Configuración de la página web
st.set_page_config(page_title="Control de Papers - Camilo & Alejandro", layout="wide")
st.title("📊 Tablero de Avance en Línea: Papers de Investigación")
st.markdown("Gestión compartida de actividades, tiempos y responsabilidades para **Camilo Alarcón** y **Alejandro Díaz**.")

# 1. Inicializar la conexión segura con Google Sheets
try:
    conn = st.connection("gsheets", type=GSheetsConnection)
    # Leemos la hoja de cálculo usando la configuración de los Secrets
    df = conn.read(ttl=0) # ttl=0 asegura que traiga los datos frescos de la nube en cada actualización
except Exception as e:
    st.error("Error al conectar con Google Sheets. Verifica la configuración de tus Secrets.")
    st.stop()

# 2. Estructura formal de actividades y parámetros
ACTIVIDADES = [
    "Análisis estadístico y elección del modelo",
    "Escritura de la introducción",
    "Marco teórico",
    "Discusión y conclusiones",
    "Revisión completa del documento",
    "Decisión de sometimiento del paper a la revista",
    "Someter el paper",
    "Decisión por parte de la revista",
    "Acciones según decisión (Ej. Nueva revista / Re-sometimiento)"
]

RESPONSABLES = ["Camilo Alarcón", "Alejandro Díaz", "Ambos"]
ESTADOS = ["Pendiente", "En Progreso", "Completado"]

# 3. Formulario Lateral Interactivo para Actualización Manual
st.sidebar.header("📝 Registrar / Actualizar Avance")
with st.sidebar.form("formulario_avance"):
    # Si ya hay papers guardados, sugerir nombres o permitir escribir uno nuevo
    papers_existentes = list(df['Paper'].dropna().unique()) if not df.empty else []
    paper_nombre = st.text_input("Nombre del Paper", placeholder="Ej. Paper Econometría Espacial")

    actividad = st.selectbox("Fase de la Investigación", ACTIVIDADES)
    responsable = st.selectbox("Responsable de la Actividad", RESPONSABLES)
    estado = st.selectbox("Estado Actual", ESTADOS)

    fecha_inicio = st.date_input("Fecha de Inicio")
    fecha_fin = st.date_input("Fecha de Finalización (o Estimada)")

    comentarios = st.text_area("Notas / Comentarios adicionales")

    st.markdown("---")
    st.markdown("⚠️ **Flujo de decisión de la revista (Solo si aplica):**")
    decision_revista = st.radio(
        "Resultado del Dictamen:",
        ["No aplica", "Aceptado", "Comentarios Mayores", "Rechazado"]
    )

    submit_btn = st.form_submit_button("Sincronizar con la Nube")

    if submit_btn:
        if not paper_nombre.strip():
            st.error("Por favor, introduce el nombre del paper.")
        elif fecha_inicio > fecha_fin:
            st.error("La fecha de inicio no puede ser posterior a la fecha de finalización.")
        else:
            # Aplicar reglas de negocio según la decisión de la revista
            accion_texto = comentarios
            if actividad == "Decisión por parte de la revista" or decision_revista != "No aplica":
                if decision_revista == "Rechazado":
                    accion_texto = "🚨 RECHAZADO -> Acción requerida: Buscar de inmediato una nueva revista para adaptar y someter. | " + comentarios
                elif decision_revista == "Comentarios Mayores":
                    accion_texto = "⚠️ COMENTARIOS MAYORES -> Acción requerida: Realizar todos los cambios estructurales solicitados y volver a someter a la misma revista. | " + comentarios

            # Formatear las fechas estrictamente como texto AAAA-MM-DD para garantizar la compatibilidad con Excel
            nuevo_registro = pd.DataFrame([{
                "Paper": paper_nombre.strip(),
                "Actividad": actividad,
                "Responsable": responsable,
                "Estado": estado,
                "Fecha Inicio": fecha_inicio.strftime('%Y-%m-%d'),
                "Fecha Fin": fecha_fin.strftime('%Y-%m-%d'),
                "Comentarios/Acciones": accion_texto
            }])

            # Unir los datos nuevos con los existentes eliminando filas completamente vacías
            df_limpio = df.dropna(how='all')
            df_actualizado = pd.concat([df_limpio, nuevo_registro], ignore_index=True)

            # Subir la actualización a Google Sheets
            conn.update(data=df_actualizado)
            st.success("✅ Datos sincronizados correctamente en Google Sheets.")
            st.rerun()

# 4. Despliegue de Indicadores y Gráficos en el Tablero Principal
# Asegurar la conversión de fechas para graficar correctamente en la UI de Streamlit
if not df.empty and df.dropna(subset=['Paper', 'Actividad']).shape[0] > 0:
    df_visualizacion = df.dropna(subset=['Paper', 'Actividad']).copy()
    df_visualizacion['Fecha Inicio'] = pd.to_datetime(df_visualizacion['Fecha Inicio'])
    df_visualizacion['Fecha Fin'] = pd.to_datetime(df_visualizacion['Fecha Fin'])

    # Bloque de Métricas Superiores
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total de Fases Registradas", len(df_visualizacion))
    with col2:
        st.metric("Proyectos de Investigación Activos", df_visualizacion['Paper'].nunique())
    with col3:
        st.metric("Actividades Completadas", len(df_visualizacion[df_visualizacion['Estado'] == 'Completado']))

    st.markdown("---")

    # Gráfico de Cronograma (Gantt) para validación de tiempos por responsable
    st.subheader("📅 Cronograma de Tiempos y Responsables")

    fig = px.timeline(
        df_visualizacion,
        x_start="Fecha Inicio",
        x_end="Fecha Fin",
        y="Actividad",
        color="Responsable",
        facet_col="Paper",
        hover_data=["Estado", "Comentarios/Acciones"],
        title="Validación de tiempos invertidos por investigador en cada fase",
        color_discrete_sequence=px.colors.qualitative.Safe
    )
    fig.update_yaxes(autorange="reversed")  # Coloca la primera actividad al principio de la lista
    fig.update_layout(height=450, margin=dict(t=40, b=40, l=20, r=20))
    st.plotly_chart(fig, use_container_width=True)

    st.markdown("---")

    # Tabla interactiva con filtros dinámicos
    st.subheader("📋 Registro de Datos en Tiempo Real")

    filtro_paper = st.multiselect("Filtrar por Nombre del Paper", df_visualizacion['Paper'].unique())
    if filtro_paper:
        df_filtrado = df_visualizacion[df_visualizacion['Paper'].isin(filtro_paper)]
    else:
        df_filtrado = df_visualizacion

    st.dataframe(
        df_filtrado.sort_values(by="Fecha Inicio", ascending=False),
        column_config={
            "Fecha Inicio": st.column_config.DatetimeColumn("Fecha Inicio", format="YYYY-MM-DD"),
            "Fecha Fin": st.column_config.DatetimeColumn("Fecha Fin", format="YYYY-MM-DD"),
        },
        use_container_width=True,
        hide_index=True
    )
else:
    st.info("💡 La hoja de cálculo se encuentra vacía o faltan datos por rellenar. Utiliza el panel de la izquierda para registrar el primer avance de tus investigaciones.")